print("Bem-vindo ao nosso jogo de MadLibs!!!")

substantivo = input("Diga um nome: ")
adjetivo = input("Diga um adjetivo: ")
verbo = input("Diga um verbo: ")
objeto = input("Diga um objeto: ")
profissao = input("Diga uma profissão: ")
adjetivo2 = input("Diga mais um adjetivo: ")
numero = input("Diga um número: ")
animal = input("Diga um animal: ")
objeto2 = input("Diga mais um objeto: ")
objeto3 = input("Diga outro objeto: ")

print()
print("Aperte enter para ver o resultado!")
input()

print()
print("A Grande Aventura no Escritório de Tecnologia.")
print()
print(f"Um dia, o {substantivo} estava trabalhando em um projeto super {adjetivo}. De repente, o computador começou a {verbo} sozinho!")
print(f"Sem pensar duas vezes, o(a) {substantivo} pegou seu {objeto} e começou a digitar comandos como um(a) verdadeiro(a) {profissao}.")
print(f"Preciso consertar isso antes que o sistema fique {adjetivo2}! exclamou o(a) {substantivo}. Depois de {numero} tentativas, finalmente o computador respondeu: ")
print(f"O problema foi causado por um {animal} que estava no sistema!")
print(f"Com isso, o problema foi resolvido, e o(a) {substantivo} ganhou o prêmio de {objeto2} mais inovador do ano.")
print(f"Moral da história: sempre leve seu {objeto3} para o escritório, porque nunca se sabe quando você vai precisar!")